_schema: _schema
paths:
  uploads: public/uploads
  static: ''
collections_config:
  blog:
    path: content/blog
    name: Blog
    icon: event_available
    disable_url: false
    description: ''
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
    defaults:
      - scope:
        path: "content/blog"
        type: "blog"
        values:
          title: ""  # Default empty title
          date: null # Automatically set date to current date and time
  pages:
    path: content
    name: Pages
    icon: wysiwyg
    disable_url: false
    description: ''
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
base_url: uploads
editor:
  default_path:
timezone: America/Winnipeg
markdown:
  engine: commonmark
  options:
    html: true
