_schema: _schema
paths:
  uploads: public/uploads
  static: ''
collections_config:
  blog:
    path: content/blog
    name: Blog
    icon: event_available
    disable_url: false
    description: ''
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    entry_type:
      field: layout  # You can choose any field name, e.g., layout or type
      name: "Blog Entry Type"
      options:
        - label: "Post"
          value: "post"
          schema: _schema/post.schema.yml
        - label: "Note"
          value: "note"
          schema: _schema/note.schema.yml
  pages:
    path: content
    name: Pages
    icon: wysiwyg
    disable_url: false
    description: ''
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
base_url: uploads
editor:
  default_path:
timezone: America/Winnipeg
markdown:
  engine: commonmark
  options:
    html: true
