_schema: _schema
paths:
  uploads: public/uploads
  static: ''
collections_config:
  blog:
    path: content/blog
    name: Blog
    icon: event_available
    disable_url: false
    description: ''
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      Post:
        path: _schema/blog_post.yml
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        name: New post
        icon: notes
        preview:
        _editables:
        _enabled_editors:
        _inputs:
          title:
            type: text
            label: Title
            cascade: true
          date:
            type: datetime
            label: Date
            cascade: true
          tags:
            type: array
            label: Tags
            cascade: true
        _select_data:
        _structures:
        create:
        new_preview_url:
  pages:
    path: content
    name: Pages
    icon: wysiwyg
    disable_url: false
    description: ''
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
base_url: uploads
editor:
  default_path:
timezone: America/Winnipeg
markdown:
  engine: commonmark
  options:
    html: true
